// <auto-generated />
using System;
using Al3b.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Al3b.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002033631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Al3b.Api.Data.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountNote")
                        .HasColumnType("text")
                        .HasColumnName("discount_note");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_bills_session_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_bills_shift_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_bills_staff_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_bills_venue_id");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_cash_movements");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_cash_movements_shift_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_cash_movements_staff_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_cash_movements_venue_id");

                    b.ToTable("cash_movements", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_phone")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.PriceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("MultiHourlyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("multi_hourly_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("SingleHourlyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("single_hourly_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_price_categories");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_price_categories_venue_id");

                    b.ToTable("price_categories", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_products_venue_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<Guid?>("WalkInCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("walk_in_customer_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reservations_customer_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_reservations_staff_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_reservations_venue_id");

                    b.HasIndex("WalkInCustomerId")
                        .HasDatabaseName("ix_reservations_walk_in_customer_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.ReservationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reservations_units");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_reservations_units_reservation_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_reservations_units_unit_id");

                    b.ToTable("reservations_units", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_rooms_venue_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<Guid?>("WalkInCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("walk_in_customer_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sessions_customer_id");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_reservation_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_sessions_staff_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_sessions_venue_id");

                    b.HasIndex("WalkInCustomerId")
                        .HasDatabaseName("ix_sessions_walk_in_customer_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.SessionProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ordered_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sessions_products");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sessions_products_product_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_sessions_products_session_id");

                    b.ToTable("sessions_products", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.SessionUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<decimal>("HourlyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_price");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sessions_units");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_sessions_units_session_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_sessions_units_unit_id");

                    b.ToTable("sessions_units", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_staff_id");

                    b.Property<decimal?>("CountedCash")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("counted_cash");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("ExpectedCash")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("expected_cash");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_staff_id");

                    b.Property<decimal>("OpeningCash")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("opening_cash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.HasIndex("ClosedByStaffId")
                        .HasDatabaseName("ix_shifts_closed_by_staff_id");

                    b.HasIndex("OpenedByStaffId")
                        .HasDatabaseName("ix_shifts_opened_by_staff_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_shifts_venue_id");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_phone")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.StaffVenue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_venues");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_staff_venues_venue_id");

                    b.HasIndex("StaffId", "VenueId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_venues_staff_id_venue_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("staff_venues", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PriceCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_category_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("PriceCategoryId")
                        .HasDatabaseName("ix_units_price_category_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_units_room_id");

                    b.HasIndex("UnitTypeId")
                        .HasDatabaseName("ix_units_unit_type_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_units_venue_id");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.UnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_unit_types");

                    b.ToTable("unit_types", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<TimeOnly?>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.WalkInCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_walk_in_customers");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_walk_in_customers_venue_id");

                    b.ToTable("walk_in_customers", (string)null);
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Bill", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_sessions_session_id");

                    b.HasOne("Al3b.Api.Data.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_shifts_shift_id");

                    b.HasOne("Al3b.Api.Data.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_staff_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_venues_venue_id");

                    b.Navigation("Session");

                    b.Navigation("Shift");

                    b.Navigation("Staff");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.CashMovement", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cash_movements_shifts_shift_id");

                    b.HasOne("Al3b.Api.Data.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cash_movements_staff_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cash_movements_venues_venue_id");

                    b.Navigation("Shift");

                    b.Navigation("Staff");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.PriceCategory", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_categories_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Product", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reservations_customers_customer_id");

                    b.HasOne("Al3b.Api.Data.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reservations_staff_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_venues_venue_id");

                    b.HasOne("Al3b.Api.Data.Entities.WalkInCustomer", "WalkInCustomer")
                        .WithMany()
                        .HasForeignKey("WalkInCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reservations_walk_in_customers_walk_in_customer_id");

                    b.Navigation("Customer");

                    b.Navigation("Staff");

                    b.Navigation("Venue");

                    b.Navigation("WalkInCustomer");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.ReservationUnit", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_units_reservations_reservation_id");

                    b.HasOne("Al3b.Api.Data.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_units_units_unit_id");

                    b.Navigation("Reservation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Room", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Session", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_customers_customer_id");

                    b.HasOne("Al3b.Api.Data.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_reservations_reservation_id");

                    b.HasOne("Al3b.Api.Data.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_staff_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_venues_venue_id");

                    b.HasOne("Al3b.Api.Data.Entities.WalkInCustomer", "WalkInCustomer")
                        .WithMany()
                        .HasForeignKey("WalkInCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_walk_in_customers_walk_in_customer_id");

                    b.Navigation("Customer");

                    b.Navigation("Reservation");

                    b.Navigation("Staff");

                    b.Navigation("Venue");

                    b.Navigation("WalkInCustomer");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.SessionProduct", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_products_products_product_id");

                    b.HasOne("Al3b.Api.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_products_sessions_session_id");

                    b.Navigation("Product");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.SessionUnit", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_units_sessions_session_id");

                    b.HasOne("Al3b.Api.Data.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_units_units_unit_id");

                    b.Navigation("Session");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Shift", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Staff", "ClosedByStaff")
                        .WithMany()
                        .HasForeignKey("ClosedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shifts_staff_closed_by_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Staff", "OpenedByStaff")
                        .WithMany()
                        .HasForeignKey("OpenedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_staff_opened_by_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shifts_venues_venue_id");

                    b.Navigation("ClosedByStaff");

                    b.Navigation("OpenedByStaff");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.StaffVenue", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_venues_staff_staff_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_venues_venues_venue_id");

                    b.Navigation("Staff");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.Unit", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.PriceCategory", "PriceCategory")
                        .WithMany()
                        .HasForeignKey("PriceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_price_categories_price_category_id");

                    b.HasOne("Al3b.Api.Data.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_rooms_room_id");

                    b.HasOne("Al3b.Api.Data.Entities.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_unit_types_unit_type_id");

                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_venues_venue_id");

                    b.Navigation("PriceCategory");

                    b.Navigation("Room");

                    b.Navigation("UnitType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Al3b.Api.Data.Entities.WalkInCustomer", b =>
                {
                    b.HasOne("Al3b.Api.Data.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_walk_in_customers_venues_venue_id");

                    b.Navigation("Venue");
                });
#pragma warning restore 612, 618
        }
    }
}
